AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Anti Virus

Globals:
  Function:
    Timeout: 3

Resources:
  FunctionName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: udmFunction/
      Handler: index.handler
      Runtime: nodejs8.10
